### Лабораторна работа 2.
Выполнили студенты группы **6404**
- Бахаев Дмитрий В.
- Сагалов Никита Д.

**Подключение библиотек**

In [131]:
import numpy as np

**2.1. Сформировать порождающую матрицу линейного кода (7, 4, 3).**

In [132]:
I_k = np.eye(4, dtype=int)
X = np.array([[1, 1, 0],
              [1, 0, 1],
              [0, 1, 1],
              [1, 1, 1]], dtype=int)
G = np.hstack((I_k, X))

G

array([[1, 0, 0, 0, 1, 1, 0],
       [0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1]])

**2.2 Сформировать проверочную матрицу на основе порождающей.**

In [133]:
H = np.hstack((X.T, np.eye(3, dtype=int)))

H

array([[1, 1, 0, 1, 1, 0, 0],
       [1, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 1, 0, 0, 1]])

**2.3 Сформировать таблицу синдромов для всех однократных ошибок.**

In [134]:
error_patterns = np.eye(7, dtype=int)
syndrome_table = {}
for i in range(7):
    syndrome = H @ error_patterns[i] % 2
    syndrome_table[tuple(syndrome)] = i

syndrome_table

{(1, 1, 0): 0,
 (1, 0, 1): 1,
 (0, 1, 1): 2,
 (1, 1, 1): 3,
 (1, 0, 0): 4,
 (0, 1, 0): 5,
 (0, 0, 1): 6}

**2.4. Сформировать кодовое слово длины n из слова длины k. Внести однократную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться в правильности полученного слова.**

In [135]:
# Кодируем слово
k_word = np.array([1, 0, 1, 0])
code_word = k_word @ G % 2

# Вносим однократную ошибку
error = np.array([0, 0, 0, 0, 1, 0, 0])
received_word = (code_word + error) % 2

# Вычисляем синдром и исправляем ошибку
syndrome = H @ received_word % 2
if tuple(syndrome) in syndrome_table:
    error_position = syndrome_table[tuple(syndrome)]
    corrected_word = (received_word + error_patterns[error_position]) % 2
else:
    corrected_word = received_word

# Проверка
print("Начальное кодовое слово:     ", code_word)
print("Кодовое слово с ошибкой:     ", received_word)
print("Ошибка исправлена:           ", np.array_equal(code_word, corrected_word))

Начальное кодовое слово:      [1 0 1 0 1 0 1]
Кодовое слово с ошибкой:      [1 0 1 0 0 0 1]
Ошибка исправлена:            True


**2.5. Сформировать кодовое слово длины n из слова длины k. Внести двукратную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться, что полученное слово отличается от отправленного.**

In [136]:
double_error = np.array([0, 0, 0, 1, 1, 0, 0])
received_word_double_error = (code_word + double_error) % 2

syndrome_double_error = H @ received_word_double_error % 2
if tuple(syndrome_double_error) in syndrome_table:
    error_position = syndrome_table[tuple(syndrome_double_error)]
    corrected_word_double = (received_word_double_error + error_patterns[[error_position]]) % 2
else:
    corrected_word_double = received_word_double_error

print("Начальное кодовое слово:     ", code_word)
print("Кодовое слово с ошибкой:     ", received_word_double_error)
print("Ошибка исправлена:           ", np.array_equal(code_word, corrected_word_double))

Начальное кодовое слово:      [1 0 1 0 1 0 1]
Кодовое слово с ошибкой:      [1 0 1 1 0 0 1]
Ошибка исправлена:            False


**2.6. Сформировать порождающую матрицу линейного кода (n, k, 5).**

In [137]:
n = 11
k = 5
I_k = np.eye(k, dtype=int)
X = np.array([
    [1, 1, 1, 0, 1, 0],
    [1, 0, 1, 1, 0, 1],
    [0, 1, 1, 1, 0, 1],
    [1, 1, 0, 1, 1, 0],
    [0, 1, 1, 0, 1, 1]
], dtype=int)
G = np.hstack((I_k, X))
G

array([[1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1],
       [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1]])

**2.7 Сформировать проверочную матрицу на основе порождающей.**

In [138]:
H = np.hstack((X.T, np.eye(n - k, dtype=int)))
H

array([[1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1]])

**2.8 Сформировать таблицу синдромов для всех однократных и двукратных ошибок**

In [139]:
error_patterns = np.eye(n, dtype=int)
syndrome_table = {}
for i in range(n):
    syndrome = H @ error_patterns[i] % 2
    syndrome_table[tuple(syndrome)] = error_patterns[i]

# Генерируем двукратные ошибки и добавляем их в таблицу синдромов
double_error_patterns = [np.bitwise_xor(error_patterns[i], error_patterns[j]) for i, j in combinations(range(11), 2)]
for pattern in double_error_patterns:
    syndrome = H @ pattern % 2
    if tuple(syndrome) not in syndrome_table:
        syndrome_table[tuple(syndrome)] = pattern

syndrome_table

{(1, 1, 1, 0, 1, 0): array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 (1, 0, 1, 1, 0, 1): array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 (0, 1, 1, 1, 0, 1): array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]),
 (1, 1, 0, 1, 1, 0): array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 (0, 1, 1, 0, 1, 1): array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 (1, 0, 0, 0, 0, 0): array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
 (0, 1, 0, 0, 0, 0): array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 (0, 0, 1, 0, 0, 0): array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 (0, 0, 0, 1, 0, 0): array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 (0, 0, 0, 0, 1, 0): array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
 (0, 0, 0, 0, 0, 1): array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 (0, 1, 0, 1, 1, 1): array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 (1, 0, 0, 1, 1, 1): array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]),
 (0, 0, 1, 1, 0, 0): array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 (1, 0, 0, 0, 0, 1): array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 (0, 1, 1, 0, 1, 0): array([1, 0, 0, 0, 0, 1, 0, 0, 0, 

**2.9. Сформировать кодовое слово длины n из слова длины k. Внести однократную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться в правильности полученного слова.**

In [140]:
# Кодируем слово
k_word = np.array([1, 0, 1, 0, 1])
code_word = k_word @ G % 2

# Вносим однократную ошибку
error = np.array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])
received_word = (code_word + error) % 2

# Вычисляем синдром и исправляем ошибку
syndrome = H @ received_word % 2
if tuple(syndrome) in syndrome_table:
    syndrome = syndrome_table[tuple(syndrome)]
    corrected_word = (received_word + syndrome) % 2
else:
    corrected_word = received_word

# Проверка
print("Начальное кодовое слово:     ", code_word)
print("Кодовое слово с ошибкой:     ", received_word)
print("Ошибка исправлена:           ", np.array_equal(code_word, corrected_word))

Начальное кодовое слово:      [1 0 1 0 1 1 1 1 1 0 0]
Кодовое слово с ошибкой:      [1 0 1 0 1 1 0 1 1 0 0]
Ошибка исправлена:            True


**2.10. Сформировать кодовое слово длины n из слова длины k. Внести двукратную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться в правильности полученного слова.**

In [141]:
double_error = np.array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0])
received_word_double_error = (code_word + double_error) % 2

syndrome_double_error = H @ received_word_double_error % 2
if tuple(syndrome_double_error) in syndrome_table:
    syndrome = syndrome_table[tuple(syndrome_double_error)]
    corrected_word_double = (received_word_double_error + syndrome) % 2
else:
    corrected_word_double = received_word_double_error

print("Received Word (Double Error):", received_word_double_error)
print("Corrected Word (Double Error):", corrected_word_double)
syndrome_double_error

Received Word (Double Error): [1 0 0 1 1 1 1 1 1 0 0]
Corrected Word (Double Error): [1 0 1 0 1 1 1 1 1 0 0]


array([1, 0, 1, 0, 1, 1], dtype=int32)