### Лабораторна работа 2.
Выполнили студенты группы **6404**
- Бахаев Дмитрий В.
- Сагалов Никита Д.

**Подключение библиотек**

In [161]:
import numpy as np

**2.1. Сформировать порождающую матрицу линейного кода (7, 4, 3).**

In [162]:
I_k = np.eye(4, dtype=int)
X = np.array([[1, 1, 0],
              [1, 0, 1],
              [0, 1, 1],
              [1, 1, 1]], dtype=int)
G = np.hstack((I_k, X))

G

array([[1, 0, 0, 0, 1, 1, 0],
       [0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1]])

**2.2 Сформировать проверочную матрицу на основе порождающей.**

In [163]:
H = np.vstack((np.eye(3, dtype=int), X))

H

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 1, 0],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

**2.3 Сформировать таблицу синдромов для всех однократных ошибок.**

In [164]:
error_patterns = np.eye(7, dtype=int)
syndrome_table = {}
for i in range(7):
    syndrome = error_patterns[i] @ H % 2
    syndrome_table[tuple(syndrome)] = error_patterns[i]

syndrome_table

{(1, 0, 0): array([1, 0, 0, 0, 0, 0, 0]),
 (0, 1, 0): array([0, 1, 0, 0, 0, 0, 0]),
 (0, 0, 1): array([0, 0, 1, 0, 0, 0, 0]),
 (1, 1, 0): array([0, 0, 0, 1, 0, 0, 0]),
 (1, 0, 1): array([0, 0, 0, 0, 1, 0, 0]),
 (0, 1, 1): array([0, 0, 0, 0, 0, 1, 0]),
 (1, 1, 1): array([0, 0, 0, 0, 0, 0, 1])}

**2.4. Сформировать кодовое слово длины n из слова длины k. Внести однократную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться в правильности полученного слова.**

In [165]:
# Кодируем слово
k_word = np.array([1, 1, 1, 1])
code_word = k_word @ G % 2

# Вносим однократную ошибку
error = np.array([0, 0, 0, 0, 1, 0, 0])
received_word = (code_word + error) % 2

# Вычисляем синдром и исправляем ошибку
syndrome = received_word @ H % 2
if tuple(syndrome) in syndrome_table:
    error_position = syndrome_table[tuple(syndrome)]
    corrected_word = (received_word + error_position) % 2
else:
    corrected_word = received_word

# Проверка
print("Начальное кодовое слово:     ", code_word)
print("Кодовое слово с ошибкой:     ", received_word)
print("Ошибка исправлена:           ", np.array_equal(code_word, corrected_word))

Начальное кодовое слово:      [1 1 1 1 1 1 1]
Кодовое слово с ошибкой:      [1 1 1 1 0 1 1]
Ошибка исправлена:            True


**2.5. Сформировать кодовое слово длины n из слова длины k. Внести двукратную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться, что полученное слово отличается от отправленного.**

In [166]:
double_error = np.array([0, 0, 0, 1, 1, 0, 0])
received_word_double_error = (code_word + double_error) % 2

syndrome_double_error = received_word_double_error @ H % 2
if tuple(syndrome_double_error) in syndrome_table:
    error_position = syndrome_table[tuple(syndrome_double_error)]
    corrected_word_double = (received_word_double_error + error_position) % 2
else:
    corrected_word_double = received_word_double_error

print("Начальное кодовое слово:     ", code_word)
print("Кодовое слово с ошибкой:     ", received_word_double_error)
print("Ошибка исправлена:           ", np.array_equal(code_word, corrected_word_double))

Начальное кодовое слово:      [1 1 1 1 1 1 1]
Кодовое слово с ошибкой:      [1 1 1 0 0 1 1]
Ошибка исправлена:            False


**2.6. Сформировать порождающую матрицу линейного кода (n, k, 5).**

In [167]:
n = 12
k = 4
I_k = np.eye(k, dtype=int)
X = np.array([
    [1, 1, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 1, 1, 1],
    [0, 0, 1, 1, 0, 0, 1, 1],
    [1, 0, 1, 0, 1, 0, 1, 0],
], dtype=int)
G = np.hstack((I_k, X))

G

array([[1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0]])

**2.7 Сформировать проверочную матрицу на основе порождающей.**

In [168]:
H = np.vstack((X, np.eye(n - k, dtype=int)))

H

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

**2.8 Сформировать таблицу синдромов для всех однократных и двукратных ошибок**

In [169]:
syndroms = dict()

for i in range(H.shape[0]):
    for j in range(i, H.shape[0]):
        if i == j:
            error = np.zeros(n, dtype=int)
            error[i] = 1
            syndroms[tuple(H[i, :])] = error
        else:
            error = np.zeros(n, dtype=int)
            error[i] = 1
            error[j] = 1
            syndroms[tuple((H[i, :] + H[j, :]) % 2)] = error

syndroms

{(1, 1, 1, 1, 0, 0, 0, 0): array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 (1, 1, 1, 1, 1, 1, 1, 1): array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 (1, 1, 0, 0, 0, 0, 1, 1): array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 (0, 1, 0, 1, 1, 0, 1, 0): array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]),
 (0, 1, 1, 1, 0, 0, 0, 0): array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 (1, 0, 1, 1, 0, 0, 0, 0): array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 (1, 1, 0, 1, 0, 0, 0, 0): array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
 (1, 1, 1, 0, 0, 0, 0, 0): array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 (1, 1, 1, 1, 1, 0, 0, 0): array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 (1, 1, 1, 1, 0, 1, 0, 0): array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 (1, 1, 1, 1, 0, 0, 1, 0): array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
 (1, 1, 1, 1, 0, 0, 0, 1): array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 (0, 0, 0, 0, 1, 1, 1, 1): array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 (0, 0, 1, 1, 1, 1, 0, 0): array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 

**2.9. Сформировать кодовое слово длины n из слова длины k. Внести однократную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться в правильности полученного слова.**

In [170]:
# Кодируем слово
k_word = np.array([1, 0, 0, 0])
code_word = k_word @ G % 2

# Вносим однократную ошибку
error = np.array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
received_word = (code_word + error) % 2

# Вычисляем синдром и исправляем ошибку
syndrome = received_word @ H % 2
if tuple(syndrome) in syndroms:
    syndrome_error = syndroms[tuple(syndrome)]
    corrected_word = (received_word + syndrome_error) % 2
else:
    corrected_word = received_word

# Проверка
print("Начальное кодовое слово:     ", code_word)
print("Кодовое слово с ошибкой:     ", received_word)
print("Ошибка исправлена:           ", np.array_equal(code_word, corrected_word))

Начальное кодовое слово:      [1 0 0 0 1 1 1 1 0 0 0 0]
Кодовое слово с ошибкой:      [1 0 0 0 1 1 0 1 0 0 0 0]
Ошибка исправлена:            True


**2.10. Сформировать кодовое слово длины n из слова длины k. Внести двукратную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться в правильности полученного слова.**

In [171]:
error = np.array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0])
received_word = (code_word + error) % 2

syndrome = received_word @ H % 2
if tuple(syndrome) in syndroms:
    syndrome_error = syndroms[tuple(syndrome)]
    corrected_word = (received_word + syndrome_error) % 2
else:
    corrected_word = received_word

print("Начальное кодовое слово:     ", code_word)
print("Кодовое слово с ошибкой:     ", received_word)
print("Ошибка исправлена:           ", np.array_equal(code_word, corrected_word))

Начальное кодовое слово:      [1 0 0 0 1 1 1 1 0 0 0 0]
Кодовое слово с ошибкой:      [1 0 0 0 1 0 0 1 0 0 0 0]
Ошибка исправлена:            True


**2.11. Сформировать кодовое слово длины n из слова длины k. Внести трёхкратную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться, что полученное слово отличается от отправленного.**

In [172]:
error = np.array([0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0])
received_word = (code_word + error) % 2

syndrome = received_word @ H % 2
if tuple(syndrome) in syndroms:
    syndrome_error = syndroms[tuple(syndrome)]
    corrected_word = (received_word + syndrome_error) % 2
else:
    corrected_word = received_word

print("Начальное кодовое слово:     ", code_word)
print("Кодовое слово с ошибкой:     ", received_word)
print("Ошибка исправлена:           ", np.array_equal(code_word, corrected_word))

Начальное кодовое слово:      [1 0 0 0 1 1 1 1 0 0 0 0]
Кодовое слово с ошибкой:      [1 0 0 0 0 0 0 1 0 0 0 0]
Ошибка исправлена:            False
