### Лабораторна работа 4.
Выполнили студенты группы **6404**
- Бахаев Дмитрий В.
- Сагалов Никита Д.

**4.1 Написать функцию формирования порождающей и проверочной матриц расширенного кода Голея (24,12,8).**

In [1]:
import numpy as np

In [2]:
def golay_matrices():
    # Порождающая матрица кода Голея
    G = np.array([
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
    ])

    return G, G.T

G, H = golay_matrices()
print("G\n", G, "\n")
print("H\n", H, "\n")

G
 [[1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 1 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0]] 

H
 [[1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 0 1 1 1 0 0 0 1 0 1]
 [1 0 1 1 1 0 0 0 1 0 1 1]
 

**4.2. Провести исследование расширенного кода Голея для одно-, двух-, трёх- и четырёхкратных ошибок.**

In [3]:
def gen_n_error_word(size, n, G):
    # Кодируем слово
    k_word = np.array([1] + [0] * (size - 1))
    code_word = k_word @ G % 2

    # Вносим n-кратную ошибку
    error = np.array([1] * n + [0] * (G.shape[1] - n))
    received_word = (code_word + error) % 2

    return code_word, received_word


def detect_error(word, G, H):
    B = G[:,12:]
    syndrome = (word @ H) % 2
    error_vector = None
    
    if np.sum(syndrome) <= 3:
        error_vector = np.hstack((syndrome, np.zeros_like(syndrome)))
    else:
        for idx, row in enumerate(B):
            candidate = (syndrome + row) % 2
            if np.sum(candidate) <= 2:
                error_pos = np.zeros_like(syndrome)
                error_pos[idx] = 1
                error_vector = np.hstack((candidate, error_pos))
                break
    
    if error_vector is None:
        syndrome_proj = (syndrome @ B) % 2
        if np.sum(syndrome_proj) <= 3:
            error_vector = np.hstack((np.zeros_like(syndrome), syndrome_proj))
        else:
            for idx, row in enumerate(B):
                candidate = (syndrome_proj + row) % 2
                if np.sum(candidate) <= 2:
                    error_pos = np.zeros_like(syndrome)
                    error_pos[idx] = 1
                    error_vector = np.hstack((error_pos, candidate))
                    break
    
    if error_vector is None:
        return None
    else:
        return (word + error_vector) % 2


def test(G, H):
    print("==============================")
    for n in range(1, 5):
        word, error_word = gen_n_error_word(12, n, G)
        corrected_word = detect_error(error_word, G, H)
        
        print("Количество ошибок:                   ", n)
        print("Начальное закодированное слово:      ", word)
        print("Закодированное слово с ошибками:     ", error_word)
        print("Ошибка исправлена:                   ", np.array_equal(word, corrected_word))
        print("------------------------------")

In [4]:
test(G, H)

Количество ошибок:                    1
Начальное закодированное слово:       [1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
Закодированное слово с ошибками:      [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
Ошибка исправлена:                    True
------------------------------
Количество ошибок:                    2
Начальное закодированное слово:       [1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
Закодированное слово с ошибками:      [0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
Ошибка исправлена:                    True
------------------------------
Количество ошибок:                    3
Начальное закодированное слово:       [1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
Закодированное слово с ошибками:      [0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
Ошибка исправлена:                    True
------------------------------
Количество ошибок:                    4
Начальное закодированное слово:       [1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
За

**4.3 Написать функцию формирования порождающей и проверочных матриц кода Рида-Маллера 𝑅𝑀(𝑟, 𝑚) на основе параметров 𝑟 и 𝑚.**

In [5]:
def rm_matrix(r, m):
    if r == 0:
        return np.ones((1, 2**m), dtype=int)
    
    if r == m:
        return np.vstack((
            rm_matrix(m-1, m),
            np.array([0] * (2**m - 1) + [1], dtype=int)
        ))
            
    return np.vstack((
        np.hstack((rm_matrix(r, m-1), rm_matrix(r, m-1))),
        np.hstack((np.zeros((1, 2**(m-1)), dtype=int), rm_matrix(r-1, m-1)))
    ))


def rm_check_matrix(H, i, m):
    return np.ones((1, 2**(m-i)), dtype=int) @ H @ np.ones((1, 2**(i-1)), dtype=int)

r, m = 1, 3

G = rm_matrix(r, m)
print("G\n", G, "\n")

G
 [[1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1]] 



**4.4. Провести исследование кода Рида-Маллера 𝑅𝑀(1,3) для одно- и двукратных ошибок.**

In [6]:
def kronecker_product(A, B):
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape
    result = np.zeros((rows_A * rows_B, cols_A * cols_B), dtype=A.dtype)

    for i in range(rows_A):
        for j in range(cols_A):
            result[i * rows_B:(i + 1) * rows_B, j * cols_B:(j + 1) * cols_B] = A[i, j] * B
    return result

def rm_check_matrix(H, m, level):
    identity_part = np.eye(2 ** (m - level), dtype=int)
    hadamard_part = kronecker_product(identity_part, H)
    padding_part = kronecker_product(hadamard_part, np.eye(2 ** (level - 1)))
    return padding_part


def test_rm(word, original_encoded_message, generator_matrix, m):
    received_message = np.copy(word)
    received_message[received_message == 0] = -1
    decoding_steps = []
    H = np.array([[1, 1], [1, -1]])
    decoding_steps.append(received_message @ rm_check_matrix(H, m, 1))
    for level in range(2, m + 1):
        decoding_steps.append(decoding_steps[-1] @ rm_check_matrix(H, m, level))

    max_value = decoding_steps[0][0]
    error_position = -1
    for step in decoding_steps:
        for idx, value in enumerate(step):
            if abs(value) > abs(max_value):
                max_value = value
                error_position = idx
    
    print("Начальное закодированное слово:      ", original_encoded_message)
    print("Закодированное слово с ошибками:     ", word)

    max_count = sum(abs(value) == abs(max_value) for step in decoding_steps for value in step)
    if max_count > 1:
        print("Ошибка исправлена:                   ", False)
        return
    
    corrected_message = list(map(int, format(error_position, f'0{m}b')))
    corrected_message.append(1 if max_value > 0 else 0)
    re_encoded_message = np.array(corrected_message[::-1]) @ generator_matrix % 2

    print("Ошибка исправлена:                   ", np.array_equal(original_encoded_message, re_encoded_message))

In [7]:
r, m = 1, 3
G = rm_matrix(r, m)
print("==============================")
for n in range(1, 3):
    print("Количество ошибок:                   ", n)
    word, error_word = gen_n_error_word(G.shape[0], n, G)
    test_rm(error_word, word, G, m)
    print("------------------------------")

Количество ошибок:                    1
Начальное закодированное слово:       [1 1 1 1 1 1 1 1]
Закодированное слово с ошибками:      [0 1 1 1 1 1 1 1]
Ошибка исправлена:                    True
------------------------------
Количество ошибок:                    2
Начальное закодированное слово:       [1 1 1 1 1 1 1 1]
Закодированное слово с ошибками:      [0 0 1 1 1 1 1 1]
Ошибка исправлена:                    False
------------------------------


**4.5. Провести исследование кода Рида-Маллера 𝑅𝑀(1,4) для одно-, двух-, трёх- и четырёхкратных ошибок.**

In [8]:
r, m = 1, 4
G = rm_matrix(r, m)
print("==============================")
for n in range(1, 5):
    print("Количество ошибок:                   ", n)
    word, error_word = gen_n_error_word(G.shape[0], n, G)
    test_rm(error_word, word, G, m)
    print("------------------------------")

Количество ошибок:                    1
Начальное закодированное слово:       [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Закодированное слово с ошибками:      [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Ошибка исправлена:                    True
------------------------------
Количество ошибок:                    2
Начальное закодированное слово:       [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Закодированное слово с ошибками:      [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Ошибка исправлена:                    True
------------------------------
Количество ошибок:                    3
Начальное закодированное слово:       [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Закодированное слово с ошибками:      [0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
Ошибка исправлена:                    True
------------------------------
Количество ошибок:                    4
Начальное закодированное слово:       [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Закодированное слово с ошибками:      [0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
Ошибка исправлена:                    Fals