### Лабораторна работа 1.
Выполнили студенты группы **6404**
- Бахаев Дмитрий В.
- Сагалов Никита Д.

**Подключение библиотек**

In [1]:
import numpy as np

**1.1. Реализация функции REF(), приводящей матрицу к ступенчатому виду**

In [45]:
import numpy as np

def REF(matrix):
    """
    matrix: Входная двумерная numpy матрица целых чисел
    return: Матрица в ступенчатом виде по модулю 2
    """
    matrix = matrix % 2
    
    rows, cols = matrix.shape
    lead = 0
    
    for r in range(rows):
        if lead >= cols:
            return matrix
        
        i = r
        while matrix[i, lead] == 0:
            i += 1
            if i == rows:
                i = r
                lead += 1
                if lead == cols:
                    return matrix
        
        # Меняем строки местами
        matrix[[i, r]] = matrix[[r, i]]

        # Зануляем все строки под ведущим элементом
        for i in range(rows):
            if i != r:
                if matrix[i, lead] == 1:
                    matrix[i] = (matrix[i] + matrix[r]) % 2
        
        lead += 1
        
    return matrix

Проверка работы

In [47]:
matrix = np.array([[3, 0, 2, 4, 5],
                  [0, 0, 5, 6, 7],
                  [0, 8, 3, -2, 5],
                  [0, 1, 0, 1, 0]])

REF(matrix)

array([[1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0]], dtype=int32)

**1.2. Реализация функции PREF(), которая приводит матрицу к приведённому ступенчатому виду**

In [50]:
import numpy as np

def RREF(matrix):
    """
    matrix: Входная двумерная numpy матрица целых чисел
    return: Матрица в приведённом ступенчатом виде по модулю 2
    """
    matrix = matrix % 2
    
    rows, cols = matrix.shape
    row = 0
    
    for col in range(cols):
        # Находим ненулевой элемент в текущем столбце 
        # начиная с текущей строки
        if row >= rows:
            break
        for i in range(row, rows):
            if matrix[i, col] == 1:
                # Меняем строки местами если необходимо
                if i != row:
                    matrix[[row, i]] = matrix[[i, row]]
                break
        else:
            # Переход к следующему столбцу
            continue

        # Обнуляем все элементы выше и ниже ведущего
        for i in range(rows):
            if i != row and matrix[i, col] == 1:
                matrix[i] = (matrix[i] + matrix[row]) % 2

        # Переходим к следующей строке
        row += 1
    
    # Удаляем нулевые строки
    matrix = matrix[~np.all(matrix == 0, axis=1)]

    return matrix

Проверка работы

In [52]:
matrix = np.array([[3, 2, 1],
                   [5, 4, 4],
                   [7, 6, 6]])

RREF(matrix)

array([[1, 0, 0],
       [0, 0, 1]], dtype=int32)

**1.3.1. Формирование порождающей матрицы в ступенчатом на основе входной**

In [54]:
S = np.array([
    [1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
    [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
    [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0]])

S_REF = REF(S)
S_REF

array([[1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

**1.3.2. Получение количества строк и столбцов**

In [57]:
print('n, k = %d, %d' % (S.shape[0], S.shape[1]))

n, k = 6, 11


**1.3.3. Формирование проверочной матрицы на основе порождающей**

Шаг 1

In [89]:
# Шаг 1
G = np.array([
    [1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
    [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

G_RREF = RREF(G)
print('G* =\n', G_RREF)

G* =
 [[1 0 1 0 0 1 0 1 0 1 0]
 [0 0 0 1 0 1 0 0 0 1 1]
 [0 0 0 0 1 0 0 1 0 0 1]
 [0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 1 1]]


Шаг 2

In [95]:
lead = []

for row in range(G_RREF.shape[0]):
    for col in range(G_RREF.shape[1]):
        if G_RREF[row][col]:
            lead.append(col)
            break
            
print('lead =', lead)

lead = [0, 3, 4, 6, 8]


Шаг 3

In [93]:
X = np.empty(
    [G_RREF.shape[0], G_RREF.shape[1]-len(lead)], 
    dtype=int
)

pos = 0
for i in range(G_RREF.shape[1]):
    if i not in lead:
        X[:, pos] = G_RREF[:, i]
        pos += 1
        
print('X =\n', X)

X =
 [[0 1 1 1 1 0]
 [0 0 1 0 1 1]
 [0 0 0 1 0 1]
 [0 0 0 0 1 0]
 [0 0 0 0 1 1]]


Шаг 4

In [98]:
I = np.eye(max(X.shape))

H = np.empty(
    [X.shape[0]+I.shape[0], X.shape[1]],
    dtype=int
)

posX, posI = 0, 0
for i in range(H.shape[0]):
    if i in lead:
        H[i, :] = X[posX, :]
        posX += 1
    else:
        H[i, :] = I[posI, :]
        posI += 1

print('H =\n', H)

H =
 [[0 1 1 1 1 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 1 1]
 [0 0 0 1 0 1]
 [0 0 1 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 1]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


**1.4 Формирование кодовых слов длины *n***

**1.4.1. Сложение слов из пораждающего множества с сохранением неповторяющихся** 